name: Auto Release on Theme Update

on:
  push:
    paths:
      - 'recoveryCordTheme.css'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: "Auto Release - ${{ steps.date.outputs.date }}"
          tag_name: "auto-release-${{ steps.date.outputs.date }}"
          files: recoveryCordTheme.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
